// Master list of clients — official order as of 2026-04-09
export const DEFAULT_CLIENTS = [
  "Dobson",
  "Creekside",
  "Pilot Mountain",
  "King",
  "Elkin",
  "East Bend",
  "JMS Brunswick",
  "JMS Holly Springs",
  "JMS Jensen Beach",
  "JMS Mooresville",
  "JMS Mooresville 2",
  "JMS Mooresville 3",
  "JMS Rural Hall",
  "JMS Salisbury",
  "Canton",
  "NWA Storage",
  "CJ Trust",
  "Hartland",
  "Kenosha",
  "Lakeland",
  "Madison",
  "1912 Walton",
  "8th St",
  "Airport",
  "Broyles",
  "Centerton",
  "Joyce",
  "NWA Storage Old",
  "Oak St",
  "Pleasant St 1",
  "Pleasant St 2",
  "Robinson",
  "Shady Grove",
  "Trafalgar",
  "Walton",
  "Fond du Lac",
  "Fond du Lac Business Savings",
  "Lakeside Truck Rentals",
];
