// Master list of clients from n8n workflow
export const DEFAULT_CLIENTS = [
  "Dobson",
  "Creekside Apartments",
  "Pilot Mountain",
  "King",
  "Elkin",
  "East Bend",
  "JMS Brunswick",
  "JMS HOLLY SPRINGS LLC",
  "JMS Holly Springs LLC",
  "JMS Jensen Beach",
  "JMS Mooresville",
  "JMS Mooresville 2",
  "JMS Mooresville 3",
  "JMS Rural Hall",
  "JMS SALISBURY",
  "JMS Salisbury",
  "Canton",
  "NWA",
  "CJ Trust",
  "Hartland",
  "Kenosha",
  "Lakeland",
  "Madison",
  "1912 Walton",
  "8th Street",
  "Airport Blvd",
  "Broyles Street",
  "Centerton",
  "Joyce",
  "Oak Street",
  "Pleasant Street 1",
  "Pleasant Street 2",
  "Robinson",
  "Shady Grove",
  "Trafalgar",
  "Walton",
  "Fond du Lac",
  "Fond du Lac Business Savings",
  "Lakeside Truck Rentals",
];
